name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  packages:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install nasm
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make x86_64
      working-directory: ./src
      run: make os-image.bin arch=x86_64
