name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
    - working-directory: ./src
      run: ./configure
    - name: make x86_64
      run: make os-image.bin arch=x86_64
