name: Build OS Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make x86_64
      working-directory: ./src
      run: nsudo apt-get install -y nasm && make os-image.bin arch=x86_64
